-- ============================================================
-- Crear esquema para tablas de localización Brasil

-- Tabla estados_br
-- Unificar definición de estados_br y cidades_br para evitar duplicación
DROP TABLE IF EXISTS public.cidades_br;
DROP TABLE IF EXISTS public.estados_br;

CREATE TABLE IF NOT EXISTS public.estados_br (
    uf TEXT PRIMARY KEY,
    nome TEXT NOT NULL,
    regiao TEXT NOT NULL,
    ibge_id INTEGER UNIQUE NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    atualizado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT estados_br_uf_len CHECK (char_length(uf) = 2)
);

CREATE INDEX IF NOT EXISTS estados_br_nome_idx ON public.estados_br (nome);

CREATE TABLE IF NOT EXISTS public.cidades_br (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ibge_id INTEGER UNIQUE NOT NULL,
    nome TEXT NOT NULL,
    uf TEXT NOT NULL,
    capital BOOLEAN NOT NULL DEFAULT FALSE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    atualizado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT cidades_br_nome_len CHECK (char_length(nome) > 0),
    CONSTRAINT fk_cidades_uf FOREIGN KEY(uf) REFERENCES public.estados_br(uf) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS cidades_br_uf_nome_idx ON public.cidades_br (uf, nome);
CREATE INDEX IF NOT EXISTS cidades_br_ibge_idx ON public.cidades_br (ibge_id);
-- Permisos RLS y Grants

-- Permitir solo lectura a anon y authenticated en estados_br y cidades_br
REVOKE ALL ON public.estados_br FROM public;
REVOKE ALL ON public.cidades_br FROM public;

GRANT SELECT ON public.estados_br TO anon, authenticated;
GRANT SELECT ON public.cidades_br TO anon, authenticated;

-- Permitir modificaciones solo a authenticated
GRANT INSERT, UPDATE, DELETE ON public.estados_br TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.cidades_br TO authenticated;

-- Insertar datos semilla para estados_br y cidades_br (extracto demo, el completo debe usarse luego)

INSERT INTO public.estados_br (uf, nome, regiao, ibge_id, ativo)
VALUES
('AC', 'ACRE', 'Norte', 12, TRUE),
('AL', 'ALAGOAS', 'Nordeste', 27, TRUE),
('AP', 'AMAPÁ', 'Norte', 16, TRUE),
('AM', 'AMAZONAS', 'Norte', 13, TRUE),
('BA', 'BAHIA', 'Nordeste', 29, TRUE),
('CE', 'CEARÁ', 'Nordeste', 23, TRUE),
('DF', 'DISTRITO FEDERAL', 'Centro-Oeste', 53, TRUE),
('ES', 'ESPÍRITO SANTO', 'Sudeste', 32, TRUE),
('GO', 'GOIÁS', 'Centro-Oeste', 52, TRUE),
('MA', 'MARANHÃO', 'Nordeste', 21, TRUE),
('MT', 'MATO GROSSO', 'Centro-Oeste', 51, TRUE),
('MS', 'MATO GROSSO DO SUL', 'Centro-Oeste', 50, TRUE),
('MG', 'MINAS GERAIS', 'Sudeste', 31, TRUE),
('PA', 'PARÁ', 'Norte', 15, TRUE),
('PB', 'PARAÍBA', 'Nordeste', 25, TRUE),
('PR', 'PARANÁ', 'Sul', 41, TRUE),
('PE', 'PERNAMBUCO', 'Nordeste', 26, TRUE),
('PI', 'PIAUÍ', 'Nordeste', 22, TRUE),
('RJ', 'RIO DE JANEIRO', 'Sudeste', 33, TRUE),
('RN', 'RIO GRANDE DO NORTE', 'Nordeste', 24, TRUE),
('RS', 'RIO GRANDE DO SUL', 'Sul', 43, TRUE),
('RO', 'RONDÔNIA', 'Norte', 11, TRUE),
('RR', 'RORAIMA', 'Norte', 14, TRUE),
('SC', 'SANTA CATARINA', 'Sul', 42, TRUE),
('SP', 'SÃO PAULO', 'Sudeste', 35, TRUE),
('SE', 'SERGIPE', 'Nordeste', 28, TRUE),
('TO', 'TOCANTINS', 'Norte', 17, TRUE)
ON CONFLICT (uf) DO NOTHING;

-- Nota: La inserción de cidades_br debe ser cargada con todo el catálogo IBGE completo a partir de un script adicional de carga (no incluido aquí por tamaño).

-- Triggers para actualización automática de updated_at

CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_timestamp_estados ON public.estados_br;
CREATE TRIGGER set_timestamp_estados
BEFORE UPDATE ON public.estados_br
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();

DROP TRIGGER IF EXISTS set_timestamp_cidades ON public.cidades_br;
CREATE TRIGGER set_timestamp_cidades
BEFORE UPDATE ON public.cidades_br
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();

-- SUPABASE / POSTGRES — Esquema de trámites y dashboard
-- Basado en las tablas existentes: entradas, clientes, salidas,
-- historial_cambios.
--
-- Objetivo:
-- - Catálogos de trámites
-- - Historial de precios
-- - Vistas operativas para la SPA
-- - Resumen mensual para KPIs y gráficos
-- ============================================================

-- ============================================================
-- 1) CATÁLOGOS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.tramites_categorias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo text NOT NULL UNIQUE,
  nombre text NOT NULL,
  descripcion text,
  color text,
  orden integer NOT NULL DEFAULT 0,
  activo boolean NOT NULL DEFAULT true,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.tramites_catalogo (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo text NOT NULL UNIQUE,
  nombre text NOT NULL,
  descripcion text,
  categoria_id bigint REFERENCES public.tramites_categorias(id) ON DELETE SET NULL,
  precio_base numeric(12,2) NOT NULL DEFAULT 0,
  costo_base numeric(12,2) NOT NULL DEFAULT 0,
  margen_objetivo numeric(8,4) NOT NULL DEFAULT 0,
  moneda text NOT NULL DEFAULT 'BRL',
  color text,
  orden integer NOT NULL DEFAULT 0,
  activo boolean NOT NULL DEFAULT true,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tramites_catalogo_precio_chk CHECK (precio_base >= 0),
  CONSTRAINT tramites_catalogo_costo_chk CHECK (costo_base >= 0)
);

CREATE TABLE IF NOT EXISTS public.tramites_precios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tramite_id bigint NOT NULL REFERENCES public.tramites_catalogo(id) ON DELETE CASCADE,
  precio numeric(12,2) NOT NULL,
  costo numeric(12,2) NOT NULL DEFAULT 0,
  moneda text NOT NULL DEFAULT 'BRL',
  vigente_desde date NOT NULL DEFAULT CURRENT_DATE,
  vigente_hasta date,
  activo boolean NOT NULL DEFAULT true,
  observaciones text,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tramites_precios_fechas_chk CHECK (vigente_hasta IS NULL OR vigente_hasta >= vigente_desde),
  CONSTRAINT tramites_precios_precio_chk CHECK (precio >= 0),
  CONSTRAINT tramites_precios_costo_chk CHECK (costo >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS tramites_precios_unico_vigencia
  ON public.tramites_precios (tramite_id, vigente_desde);

CREATE INDEX IF NOT EXISTS tramites_catalogo_categoria_idx
  ON public.tramites_catalogo (categoria_id, activo, orden);

CREATE INDEX IF NOT EXISTS tramites_catalogo_codigo_idx
  ON public.tramites_catalogo (codigo);

CREATE INDEX IF NOT EXISTS tramites_precios_tramite_idx
  ON public.tramites_precios (tramite_id, activo, vigente_desde DESC);

-- ============================================================
-- 1B) CATÁLOGO GEOGRÁFICO BRASIL (UF + CIUDADES)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.estados_br (
  uf text PRIMARY KEY,
  nome text NOT NULL,
  regiao text,
  ibge_id integer UNIQUE,
  ativo boolean NOT NULL DEFAULT true,
  criado_en timestamptz NOT NULL DEFAULT now(),
  atualizado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT estados_br_uf_chk CHECK (char_length(uf) = 2),
  CONSTRAINT estados_br_nome_chk CHECK (char_length(nome) > 0)
);

CREATE TABLE IF NOT EXISTS public.cidades_br (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ibge_id integer UNIQUE NOT NULL,
  nome text NOT NULL,
  uf text NOT NULL REFERENCES public.estados_br(uf) ON DELETE CASCADE,
  capital boolean NOT NULL DEFAULT false,
  ativo boolean NOT NULL DEFAULT true,
  criado_en timestamptz NOT NULL DEFAULT now(),
  atualizado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cidades_br_nome_chk CHECK (char_length(nome) > 0)
);

CREATE INDEX IF NOT EXISTS estados_br_nome_idx
  ON public.estados_br (nome);

CREATE INDEX IF NOT EXISTS cidades_br_uf_nome_idx
  ON public.cidades_br (uf, nome);

CREATE INDEX IF NOT EXISTS cidades_br_ibge_idx
  ON public.cidades_br (ibge_id);

-- ============================================================
-- 2) RLS PARA CATÁLOGOS
-- ============================================================

ALTER TABLE public.tramites_categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tramites_catalogo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tramites_precios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estados_br ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cidades_br ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "dashboard_read_tramites_categorias" ON public.tramites_categorias;
CREATE POLICY "dashboard_read_tramites_categorias" ON public.tramites_categorias
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "dashboard_read_tramites_catalogo" ON public.tramites_catalogo;
CREATE POLICY "dashboard_read_tramites_catalogo" ON public.tramites_catalogo
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "dashboard_read_tramites_precios" ON public.tramites_precios;
CREATE POLICY "dashboard_read_tramites_precios" ON public.tramites_precios
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "dashboard_write_tramites_categorias" ON public.tramites_categorias;
CREATE POLICY "dashboard_write_tramites_categorias" ON public.tramites_categorias
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "dashboard_write_tramites_catalogo" ON public.tramites_catalogo;
CREATE POLICY "dashboard_write_tramites_catalogo" ON public.tramites_catalogo
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "dashboard_write_tramites_precios" ON public.tramites_precios;
CREATE POLICY "dashboard_write_tramites_precios" ON public.tramites_precios
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "dashboard_read_estados_br" ON public.estados_br;
CREATE POLICY "dashboard_read_estados_br" ON public.estados_br
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "dashboard_read_cidades_br" ON public.cidades_br;
CREATE POLICY "dashboard_read_cidades_br" ON public.cidades_br
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "dashboard_write_estados_br" ON public.estados_br;
CREATE POLICY "dashboard_write_estados_br" ON public.estados_br
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "dashboard_write_cidades_br" ON public.cidades_br;
CREATE POLICY "dashboard_write_cidades_br" ON public.cidades_br
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- 3) VISTA DE PRECIOS VIGENTES
-- ============================================================

DROP VIEW IF EXISTS public.v_tramites_precios_vigentes CASCADE;

CREATE OR REPLACE VIEW public.v_tramites_precios_vigentes
WITH (security_invoker = true) AS
SELECT
  ranked.precio_id,
  ranked.tramite_id,
  ranked.tramite_codigo,
  ranked.tramite_nombre,
  ranked.categoria_id,
  ranked.categoria_codigo,
  ranked.categoria_nombre,
  ranked.precio,
  ranked.costo,
  ranked.moneda,
  ranked.vigente_desde,
  ranked.vigente_hasta,
  ranked.activo,
  ranked.observaciones,
  ranked.creado_en,
  ranked.actualizado_en
FROM (
  SELECT
    tp.id AS precio_id,
    tp.tramite_id,
    tc.codigo AS tramite_codigo,
    tc.nombre AS tramite_nombre,
    tc.categoria_id,
    cat.codigo AS categoria_codigo,
    cat.nombre AS categoria_nombre,
    tp.precio,
    tp.costo,
    tp.moneda,
    tp.vigente_desde,
    tp.vigente_hasta,
    tp.activo,
    tp.observaciones,
    tp.creado_en,
    tp.actualizado_en,
    ROW_NUMBER() OVER (
      PARTITION BY tp.tramite_id
      ORDER BY tp.vigente_desde DESC, tp.id DESC
    ) AS rn
  FROM public.tramites_precios tp
  JOIN public.tramites_catalogo tc
    ON tc.id = tp.tramite_id
  LEFT JOIN public.tramites_categorias cat
    ON cat.id = tc.categoria_id
  WHERE tp.activo = true
    AND tp.vigente_desde <= CURRENT_DATE
    AND (tp.vigente_hasta IS NULL OR tp.vigente_hasta >= CURRENT_DATE)
) ranked
WHERE ranked.rn = 1;

-- ============================================================
-- 4) VISTA DETALLADA DE TRÁMITES
--    Une entradas + clientes + catálogo + precio vigente
-- ============================================================

DROP VIEW IF EXISTS public.v_tramites_detallado CASCADE;

CREATE OR REPLACE VIEW public.v_tramites_detallado
WITH (security_invoker = true) AS
SELECT
  e.*,
  c.nombre AS nombre_cliente,
  c.telefono AS telefono_cliente,
  c.email AS email_cliente,
  c.cpf AS cpf_cliente,
  c.pais AS pais_cliente,
  c.ciudad AS ciudad_cliente,
  c.estado_cliente,
  c.canal_adquisicion,
  c.atendente AS atendente_cliente,
  tc.id AS tramite_catalogo_id,
  tc.codigo AS tramite_codigo,
  tc.nombre AS tramite_nombre,
  cat.codigo AS categoria_codigo,
  cat.nombre AS categoria_nombre,
  COALESCE(vp.precio, tc.precio_base, e.valor, 0)::numeric(12,2) AS precio_catalogo,
  COALESCE(vp.costo, tc.costo_base, 0)::numeric(12,2) AS costo_catalogo,
  (COALESCE(vp.precio, tc.precio_base, e.valor, 0) - COALESCE(vp.costo, tc.costo_base, 0))::numeric(12,2) AS utilidad_estimada,
  CASE
    WHEN COALESCE(vp.precio, tc.precio_base, e.valor, 0) > 0
      THEN ROUND(
        (COALESCE(vp.precio, tc.precio_base, e.valor, 0) - COALESCE(vp.costo, tc.costo_base, 0))
        / COALESCE(vp.precio, tc.precio_base, e.valor, 0),
        4
      )
    ELSE NULL
  END AS margen_estimado
FROM public.entradas e
LEFT JOIN public.clientes c
  ON c.id = e.id_cliente
LEFT JOIN public.tramites_catalogo tc
  ON upper(trim(e.servicio)) = upper(trim(tc.nombre))
  OR upper(trim(e.servicio)) = upper(trim(tc.codigo))
LEFT JOIN public.tramites_categorias cat
  ON cat.id = tc.categoria_id
LEFT JOIN public.v_tramites_precios_vigentes vp
  ON vp.tramite_id = tc.id;

-- ============================================================
-- 5) VISTA POR CLIENTE
--    Totales y último trámite por cliente
-- ============================================================

DROP VIEW IF EXISTS public.v_clientes_tramites CASCADE;

CREATE OR REPLACE VIEW public.v_clientes_tramites
WITH (security_invoker = true) AS
SELECT
  c.*,
  COUNT(e.id)::integer AS total_tramites,
  COUNT(*) FILTER (WHERE e.estado_tramite = 'pendiente')::integer AS tramites_pendientes,
  COUNT(*) FILTER (WHERE e.estado_tramite = 'procesando')::integer AS tramites_procesando,
  COUNT(*) FILTER (WHERE e.estado_tramite = 'completada')::integer AS tramites_completados,
  COUNT(*) FILTER (WHERE e.estado_tramite = 'cancelada')::integer AS tramites_cancelados,
  COALESCE(SUM(CASE WHEN e.estado_tramite = 'completada' THEN e.valor ELSE 0 END), 0)::numeric AS valor_completado,
  COALESCE(SUM(CASE WHEN e.estado_tramite IN ('pendiente', 'procesando') THEN e.valor ELSE 0 END), 0)::numeric AS valor_pipeline,
  MAX(COALESCE(e.fecha_completacion, e.creado_en)) AS ultima_fecha_tramite,
  MAX(e.creado_en) AS fecha_ultima_entrada
FROM public.clientes c
LEFT JOIN public.entradas e
  ON e.id_cliente = c.id
GROUP BY c.id;

-- ============================================================
-- 6) RESUMEN MENSUAL
--    Trámites, clientes nuevos y salidas
-- ============================================================

DROP VIEW IF EXISTS public.v_resumen_mensual_tramites CASCADE;

CREATE OR REPLACE VIEW public.v_resumen_mensual_tramites
WITH (security_invoker = true) AS
WITH entradas_mes AS (
  SELECT
    date_trunc('month', COALESCE(e.fecha_completacion, e.creado_en)) AS mes,
    COUNT(*)::integer AS total_tramites,
    COUNT(*) FILTER (WHERE e.estado_tramite = 'pendiente')::integer AS pendientes,
    COUNT(*) FILTER (WHERE e.estado_tramite = 'procesando')::integer AS procesando,
    COUNT(*) FILTER (WHERE e.estado_tramite = 'completada')::integer AS completadas,
    COUNT(*) FILTER (WHERE e.estado_tramite = 'cancelada')::integer AS canceladas,
    COALESCE(SUM(CASE WHEN e.estado_tramite = 'completada' THEN e.valor ELSE 0 END), 0)::numeric AS ingresos,
    COALESCE(SUM(CASE WHEN e.estado_tramite IN ('pendiente', 'procesando') THEN e.valor ELSE 0 END), 0)::numeric AS pipeline,
    COALESCE(AVG(CASE WHEN e.estado_tramite = 'completada' THEN e.valor END), 0)::numeric AS ticket_promedio,
    COUNT(DISTINCT e.id_cliente)::integer AS clientes_activos
  FROM public.entradas e
  WHERE COALESCE(e.fecha_completacion, e.creado_en) IS NOT NULL
  GROUP BY 1
),
clientes_mes AS (
  SELECT
    date_trunc('month', c.creado_en) AS mes,
    COUNT(*)::integer AS clientes_nuevos
  FROM public.clientes c
  WHERE c.creado_en IS NOT NULL
  GROUP BY 1
),
salidas_mes AS (
  SELECT
    date_trunc('month', COALESCE(s.fecha, s.creado_en)) AS mes,
    COALESCE(SUM(s.valor), 0)::numeric AS egresos
  FROM public.salidas s
  WHERE COALESCE(s.fecha, s.creado_en) IS NOT NULL
  GROUP BY 1
),
meses AS (
  SELECT mes FROM entradas_mes
  UNION
  SELECT mes FROM clientes_mes
  UNION
  SELECT mes FROM salidas_mes
)
SELECT
  m.mes,
  COALESCE(em.total_tramites, 0) AS total_tramites,
  COALESCE(em.pendientes, 0) AS pendientes,
  COALESCE(em.procesando, 0) AS procesando,
  COALESCE(em.completadas, 0) AS completadas,
  COALESCE(em.canceladas, 0) AS canceladas,
  COALESCE(em.ingresos, 0) AS ingresos,
  COALESCE(sm.egresos, 0) AS egresos,
  COALESCE(em.ingresos, 0) - COALESCE(sm.egresos, 0) AS utilidad_neta,
  COALESCE(em.pipeline, 0) AS pipeline,
  COALESCE(em.ticket_promedio, 0) AS ticket_promedio,
  COALESCE(em.clientes_activos, 0) AS clientes_activos,
  COALESCE(cm.clientes_nuevos, 0) AS clientes_nuevos
FROM meses m
LEFT JOIN entradas_mes em
  ON em.mes = m.mes
LEFT JOIN clientes_mes cm
  ON cm.mes = m.mes
LEFT JOIN salidas_mes sm
  ON sm.mes = m.mes
ORDER BY m.mes DESC;

-- ============================================================
-- 7) VISTA PRINCIPAL DEL DASHBOARD
--    KPIs del mes actual en una sola fila
-- ============================================================

DROP VIEW IF EXISTS public.v_dashboard_principal CASCADE;

CREATE OR REPLACE VIEW public.v_dashboard_principal
WITH (security_invoker = true) AS
WITH resumen AS (
  SELECT *
  FROM public.v_resumen_mensual_tramites
),
mes_actual AS (
  SELECT *
  FROM resumen
  WHERE mes = date_trunc('month', CURRENT_DATE::timestamptz)
  LIMIT 1
),
ultimo_mes AS (
  SELECT *
  FROM resumen
  ORDER BY mes DESC
  LIMIT 1
)
SELECT
  COALESCE(ma.mes, lm.mes, date_trunc('month', CURRENT_DATE::timestamptz)) AS mes,
  COALESCE(ma.total_tramites, 0) AS total_tramites,
  COALESCE(ma.completadas, 0) AS completadas,
  COALESCE(ma.pendientes, 0) AS pendientes,
  COALESCE(ma.procesando, 0) AS procesando,
  COALESCE(ma.canceladas, 0) AS canceladas,
  COALESCE(ma.ingresos, 0) AS ingresos,
  COALESCE(ma.egresos, 0) AS egresos,
  COALESCE(ma.utilidad_neta, 0) AS utilidad_neta,
  COALESCE(ma.pipeline, 0) AS pipeline,
  COALESCE(ma.ticket_promedio, 0) AS ticket_promedio,
  COALESCE(ma.clientes_activos, 0) AS clientes_activos,
  COALESCE(ma.clientes_nuevos, 0) AS clientes_nuevos,
  COALESCE(lm.total_tramites, 0) AS total_tramites_mes_anterior,
  COALESCE(lm.ingresos, 0) AS ingresos_mes_anterior,
  COALESCE(lm.utilidad_neta, 0) AS utilidad_neta_mes_anterior
FROM (SELECT 1) base
LEFT JOIN mes_actual ma
  ON true
LEFT JOIN ultimo_mes lm
  ON true;

-- ============================================================
-- 8) VISTA POR SERVICIO
--    Distribución y rentabilidad por trámite
-- ============================================================

DROP VIEW IF EXISTS public.v_dashboard_servicios CASCADE;

CREATE OR REPLACE VIEW public.v_dashboard_servicios
WITH (security_invoker = true) AS
SELECT
  COALESCE(tc.codigo, upper(trim(e.servicio))) AS codigo_servicio,
  COALESCE(tc.nombre, e.servicio, 'Sin trámite') AS nombre_servicio,
  COALESCE(cat.nombre, 'Sin categoría') AS categoria,
  COUNT(e.id)::integer AS total_tramites,
  COUNT(*) FILTER (WHERE e.estado_tramite = 'pendiente')::integer AS pendientes,
  COUNT(*) FILTER (WHERE e.estado_tramite = 'procesando')::integer AS procesando,
  COUNT(*) FILTER (WHERE e.estado_tramite = 'completada')::integer AS completadas,
  COUNT(*) FILTER (WHERE e.estado_tramite = 'cancelada')::integer AS canceladas,
  COALESCE(SUM(CASE WHEN e.estado_tramite = 'completada' THEN e.valor ELSE 0 END), 0)::numeric AS ingresos,
  COALESCE(SUM(CASE WHEN e.estado_tramite = 'completada' THEN COALESCE(vp.costo, tc.costo_base, 0) ELSE 0 END), 0)::numeric AS costo_estimado,
  COALESCE(SUM(CASE WHEN e.estado_tramite = 'completada' THEN e.valor - COALESCE(vp.costo, tc.costo_base, 0) ELSE 0 END), 0)::numeric AS utilidad_estimada,
  CASE
    WHEN COALESCE(SUM(CASE WHEN e.estado_tramite = 'completada' THEN e.valor ELSE 0 END), 0) > 0
      THEN ROUND(
        COALESCE(SUM(CASE WHEN e.estado_tramite = 'completada' THEN e.valor - COALESCE(vp.costo, tc.costo_base, 0) ELSE 0 END), 0)
        / COALESCE(SUM(CASE WHEN e.estado_tramite = 'completada' THEN e.valor ELSE 0 END), 0),
        4
      )
    ELSE NULL
  END AS margen
FROM public.entradas e
LEFT JOIN public.tramites_catalogo tc
  ON upper(trim(e.servicio)) = upper(trim(tc.nombre))
  OR upper(trim(e.servicio)) = upper(trim(tc.codigo))
LEFT JOIN public.tramites_categorias cat
  ON cat.id = tc.categoria_id
LEFT JOIN public.v_tramites_precios_vigentes vp
  ON vp.tramite_id = tc.id
GROUP BY
  COALESCE(tc.codigo, upper(trim(e.servicio))),
  COALESCE(tc.nombre, e.servicio, 'Sin trámite'),
  COALESCE(cat.nombre, 'Sin categoría')
ORDER BY ingresos DESC, total_tramites DESC;

-- ============================================================
-- 9) VISTA DE HISTORIAL DETALLADO
-- ============================================================

DROP VIEW IF EXISTS public.v_historial_detallado CASCADE;

CREATE OR REPLACE VIEW public.v_historial_detallado
WITH (security_invoker = true) AS
SELECT
  h.*,
  c.nombre AS nombre_cliente,
  e.servicio AS nombre_servicio,
  tc.codigo AS tramite_codigo,
  tc.nombre AS tramite_nombre
FROM public.historial_cambios h
LEFT JOIN public.clientes c
  ON c.id = h.id_cliente
LEFT JOIN public.entradas e
  ON e.id = h.id_entrada
LEFT JOIN public.tramites_catalogo tc
  ON upper(trim(e.servicio)) = upper(trim(tc.nombre))
  OR upper(trim(e.servicio)) = upper(trim(tc.codigo));

-- ============================================================
-- 10) RLS PARA HISTORIAL
-- ============================================================

ALTER TABLE public.historial_cambios ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "dashboard_read_historial" ON public.historial_cambios;
CREATE POLICY "dashboard_read_historial" ON public.historial_cambios
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "dashboard_write_historial" ON public.historial_cambios;
CREATE POLICY "dashboard_write_historial" ON public.historial_cambios
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- 11) FUNCIÓN TRANSACCIONAL DE BORRADO
-- ============================================================

CREATE OR REPLACE FUNCTION public.delete_entrada_cascade(p_entrada_id bigint)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  deleted_rows integer;
BEGIN
  DELETE FROM public.historial_cambios
  WHERE id_entrada = p_entrada_id;

  DELETE FROM public.entradas
  WHERE id = p_entrada_id;

  GET DIAGNOSTICS deleted_rows = ROW_COUNT;
  RETURN deleted_rows > 0;
END;
$$;

GRANT EXECUTE ON FUNCTION public.delete_entrada_cascade(bigint) TO authenticated;

-- ============================================================
-- 12) REAALTIME PARA CATÁLOGOS NUEVOS
-- ============================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'tramites_categorias'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.tramites_categorias;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'tramites_catalogo'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.tramites_catalogo;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'tramites_precios'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.tramites_precios;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'historial_cambios'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.historial_cambios;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'estados_br'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.estados_br;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'cidades_br'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.cidades_br;
  END IF;
END $$;

-- ============================================================
-- 13) GRANTS PARA VISTAS
-- ============================================================

GRANT SELECT ON public.tramites_categorias TO anon, authenticated;
GRANT SELECT ON public.tramites_catalogo TO anon, authenticated;
GRANT SELECT ON public.tramites_precios TO anon, authenticated;
GRANT SELECT ON public.estados_br TO anon, authenticated;
GRANT SELECT ON public.cidades_br TO anon, authenticated;
GRANT SELECT ON public.v_tramites_precios_vigentes TO anon, authenticated;
GRANT SELECT ON public.v_tramites_detallado TO anon, authenticated;
GRANT SELECT ON public.v_clientes_tramites TO anon, authenticated;
GRANT SELECT ON public.v_resumen_mensual_tramites TO anon, authenticated;
GRANT SELECT ON public.v_dashboard_principal TO anon, authenticated;
GRANT SELECT ON public.v_dashboard_servicios TO anon, authenticated;
GRANT SELECT ON public.v_historial_detallado TO anon, authenticated;

-- ============================================================
-- 14) SEED OPCIONAL DE TRÁMITES PRINCIPALES
--     Basado en los servicios ya visibles en la SPA.
-- ============================================================

INSERT INTO public.tramites_categorias (codigo, nombre, descripcion, color, orden)
VALUES
  ('documentacion', 'Documentación', 'Trámites de documentos y regularización', '#378ADD', 10),
  ('migracion', 'Migración', 'Procesos migratorios y estatus', '#38A169', 20),
  ('identidad', 'Identidad / CPF', 'Servicios de identidad y registros básicos', '#ED8936', 30),
  ('empleo', 'Empleo / Currículo', 'Servicios de apoyo laboral', '#805AD5', 40)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO public.tramites_catalogo (
  codigo, nombre, descripcion, categoria_id, precio_base, costo_base, margen_objetivo, moneda, color, orden
)
SELECT
  seed.codigo,
  seed.nombre,
  seed.descripcion,
  cat.id,
  seed.precio_base,
  seed.costo_base,
  seed.margen_objetivo,
  seed.moneda,
  seed.color,
  seed.orden
FROM (
  VALUES
    ('TRAD_CNH', 'TRAD. CNH', 'Traducción / CNH', 'documentacion', 120.00, 74.10, 0.6175, 'BRL', '#378ADD', 10),
    ('AG_PF', 'AG. PF.', 'Apertura / apoyo para PF', 'documentacion', 120.00, 55.50, 0.4625, 'BRL', '#38A169', 20),
    ('CAMB_END', 'CAMB. END.', 'Cambio de endereço', 'documentacion', 97.00, 22.30, 0.2300, 'BRL', '#ED8936', 30),
    ('DES_REF', 'DES. REF.', 'Desarquivamento / referência', 'documentacion', 147.00, 33.80, 0.2300, 'BRL', '#D69E2E', 40),
    ('PDF_UNICO', 'PDF UNICO', 'PDF único / consolidado', 'documentacion', 147.00, 33.80, 0.2300, 'BRL', '#6B46C1', 50),
    ('RES_PMT', 'RES. PMT.', 'Residência / PMT', 'migracion', 600.00, 138.00, 0.2300, 'BRL', '#319795', 60),
    ('VISA_REU', 'VISA REU.', 'Visa / reagrupación', 'migracion', 600.00, 138.00, 0.2300, 'BRL', '#2F855A', 70),
    ('SISCONARE', 'SISCONARE', 'Trámite en Sisconare', 'migracion', 147.00, 33.80, 0.2300, 'BRL', '#3182CE', 80),
    ('CPF', 'CPF', 'Cadastro de pessoa física', 'identidad', 80.00, 18.40, 0.2300, 'BRL', '#DD6B20', 90),
    ('CURRICULO', 'CURRICULO', 'Preparación de currículo', 'empleo', 60.00, 13.80, 0.2300, 'BRL', '#805AD5', 100)
) AS seed(codigo, nombre, descripcion, categoria_codigo, precio_base, costo_base, margen_objetivo, moneda, color, orden)
JOIN public.tramites_categorias cat
  ON cat.codigo = seed.categoria_codigo
ON CONFLICT (codigo) DO UPDATE
SET
  nombre = EXCLUDED.nombre,
  descripcion = EXCLUDED.descripcion,
  categoria_id = EXCLUDED.categoria_id,
  precio_base = EXCLUDED.precio_base,
  costo_base = EXCLUDED.costo_base,
  margen_objetivo = EXCLUDED.margen_objetivo,
  moneda = EXCLUDED.moneda,
  color = EXCLUDED.color,
  orden = EXCLUDED.orden,
  actualizado_en = now();

INSERT INTO public.tramites_precios (
  tramite_id, precio, costo, moneda, vigente_desde, activo, observaciones
)
SELECT
  tc.id,
  tc.precio_base,
  tc.costo_base,
  tc.moneda,
  CURRENT_DATE,
  true,
  'Precio inicial cargado desde el catálogo'
FROM public.tramites_catalogo tc
ON CONFLICT (tramite_id, vigente_desde) DO UPDATE
SET
  precio = EXCLUDED.precio,
  costo = EXCLUDED.costo,
  moneda = EXCLUDED.moneda,
  activo = EXCLUDED.activo,
  observaciones = EXCLUDED.observaciones,
  actualizado_en = now();

-- ============================================================
-- FIN
-- ============================================================
